### PR TITLE
Hotfix 7475

### PR DESCRIPTION
**Pull request by 202chaz**
### Redmine ticket(s)
https://devops.dchbx.org/redmine/issues/7475

### Local build result

Finished in 2 minutes 21.7 seconds (files took 6.9 seconds to load)
3861 examples, 0 failures, 73 pendings

48 scenarios (48 passed)
916 steps (916 passed)
5m44.778s

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

### CODE REVIEW

**Comment by Kevin-Wei** [comment]
@ChazHaskins This branch needs a rebase

**Comment by 202chaz** [comment]
@Kevin-Wei Rebased

**Comment by Kevin-Wei** [comment]
Being addressed by https://github.com/dchbx/enroll/pull/105

**Comment by Kevin-Wei** [comment]
resolved via https://github.com/dchbx/enroll/pull/105

**Pull request closed without merging**
