### PR TITLE
Refs #7747 - Add termination date to the 'Confirm Your Plan' page

### PR DESCRIPTION
**Pull request by hlee**
### Redmine ticket(s)
* (https://devops.dchbx.org/redmine/issues/7747)
* (https://devops.dchbx.org/redmine/issues/4772)
* ~~(https://devops.dchbx.org/redmine/issues/7856)~~
* ~~(https://devops.dchbx.org/redmine/issues/7558)~~
* (https://devops.dchbx.org/redmine/issues/7487)
* (https://devops.dchbx.org/redmine/issues/7655)

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

### CODE REVIEW

**Comment by Kevin-Wei** [comment]
@hlee this needs a rebase for a clean build

**Comment by sarathpyerra** [comment]
+1

**Comment by hlee** [comment]
will close this one and create a new one

**Comment by Kevin-Wei** [comment]
you don't have to close the PR brah

**Pull request merged**
