### PR TITLE
POCs Need Confirmation Page After Submitting Application Page

### PR DESCRIPTION
**Pull request by sarathpyerra**
### Redmine ticket(s)
* https://devops.dchbx.org/redmine/issues/7320
 
```
bundle exec rake parallel:spec[4]
Finished in 13 minutes 44 seconds (files took 29.54 seconds to load)
3777 examples, 0 failures, 73 pending

bundle exec cucumber
44 scenarios (44 passed)
881 steps (881 passed)
9m4.483s

```

### Latest rebase/merge tag
tag: 1.7.7

---

### Data ticket(s) Followup
* (redmine links here - optional)

---

#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

### CODE REVIEW

**Comment by davidplappert** [comment]
@sarathpyerra I see that this passed locally. Please check into the Jenkins error and verify that it was a one time fluke, and post your reasoning here.

**Comment by sarathpyerra** [comment]
Not an issue @davidplappert ,Flickery tests.we are good !!

**Comment by davidplappert** [comment]
@sarathpyerra What, exactly, is the issue? Any ideas for fixing the flickering test?

**Comment by Kevin-Wei** [comment]
@sarathpyerra This branch needs a rebase

**Comment by sarathpyerra** [comment]
@Kevin-Wei Rebased and pushed.

**Pull request merged**
