### PR TITLE
4284: Google Analytics Setup

### PR DESCRIPTION
**Pull request by davidplappert**
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [4284](https://devops.dchbx.org/redmine/issues/4284) |
| App-Dev Road Map # | n/a |
| Start Date | 12/09/2015 |
| Due Date | n/a  |
| App-Dev Priority | n/a |
| Development Story Points | 2 |
| Peer Review Story Points | n/a |
| Ticket Author | @davidplappert |

### CODE REVIEW

**Comment by davidplappert** [comment]
testing comment

**Comment by davidplappert** [comment]
testing comment

**Comment by davidplappert** [comment]
testing comment 333

**Comment by Kevin-Wei** [comment]
Functionality has been implemented. ?

**Pull request closed without merging**
