### PR TITLE
Deprecated: 12952: BQT-Benefit Group Button 

### PR DESCRIPTION
**Pull request by maheshkurma**
|Field|Value|
|-----|-----|
| Redmine Ticket Number | [12952](https://devops.dchbx.org/redmine/issues/12952) |
| App-Dev Road Map # | n/a |
| Start Date | n/a |
| Due Date | n/a  |
| App-Dev Priority | UP-3 |
| Development Story Points | n/a |
| Peer Review Story Points | n/a |
| Ticket Author | @Ckellem |

### CODE REVIEW

**Comment by davidplappert** [comment]
closing because of a new dup PR

**Comment by Kevin-Wei** [comment]
This isn't a dupe

**Comment by Kevin-Wei** [comment]
https://github.com/dchbx/enroll/pull/753 a fix for branches mixing.

**Comment by Kevin-Wei** [comment]
addressed via #856

**Pull request closed without merging**
