### PR TITLE
Er invoice view 5387

### PR DESCRIPTION
**Pull request by vineelsonnathi**
### Redmine ticket(s)
* (https://devops.dchbx.org/redmine/issues/7608)
* (https://devops.dchbx.org/redmine/issues/5387)

### Local build result

```
bundle exec rake parallel:spec[4]
3763 examples, 0 failures, 73 pendings
Took 143 seconds (2:23)

bundle exec cucumber
29 scenarios (29 passed)
727 steps (727 passed)
5m8.423s
```

### Latest rebase/merge tag
*

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

#### Peer Review
* 1. Verified the functionality works as expected.
* 2. All specs(rspec and cucumber) are passing
* 3. The data is taking some time to load on the ER invoices tab and during pagination. 

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

### CODE REVIEW

**Comment by Kevin-Wei** [comment]
being handled by #28

**Comment by Kevin-Wei** [comment]
resolved via https://github.com/dchbx/enroll/pull/28

**Comment by Kevin-Wei** [comment]
why did the script even grab this PR? @davidplappert

**Comment by chriswiseman-dcgov** [comment]
Kevin, David - do you need me to look at something specific here?


________________________________

**Pull request closed without merging**
