### PR TITLE
Feature 5434

### PR DESCRIPTION
**Pull request by withintheruins14**
### Redmine ticket(s)
https://devops.dchbx.org/redmine/issues/5434

### Local build result

```
Finished in 2 minutes 39.7 seconds (files took 9.09 seconds to load)
878 examples, 0 failures, 17 pending
29 scenarios (29 passed)
727 steps (727 passed)
6m12.192s
```

### Latest rebase/merge tag
tag: refs/tags/1.7.6

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

### CODE REVIEW

**Comment by davidplappert** [comment]
@withintheruins14 Please fix the merge conflicts here!

**Comment by withintheruins14** [comment]
@davidplappert fixed! thanks

**Comment by Kevin-Wei** [comment]
@withintheruins14  This branch needs a rebase

**Comment by withintheruins14** [comment]
please hold on this until 6272 passes stakeholder review

**Comment by Kevin-Wei** [comment]
@withintheruins14 6272 has been released. please rebase this

**Comment by Kevin-Wei** [comment]
@withintheruins14 friendly reminder that this build is red

**Comment by Kevin-Wei** [comment]
addressed via https://github.com/dchbx/enroll/pull/629

**Pull request closed without merging**
