### PR TITLE
Hotfix 4772

### PR DESCRIPTION
**Pull request by hlee**
### Redmine ticket(s)
* (https://devops.dchbx.org/redmine/issues/4772)
* (if more)

### Local build result

```
bundle exec rake parallel:spec[4]
bundle exec cucumber
```

### Latest rebase/merge tag
* master

---

### Data ticket(s) Followup
* (redmine links here - optional)

### Related Pull Requests
* (github links here - optional)

---

#### Peer Review
* (For code review)

#### Functional Testing
* (For testing locally)

#### Deployment
* (for release manager and/or build manager)

### CODE REVIEW

**Comment by hlee** [comment]
some code need 7040

**Comment by Kevin-Wei** [comment]
Does this create a dependency for deployment? @hlee

**Comment by hlee** [comment]
@Kevin-Wei  
yup 7040
https://devops.dchbx.org/redmine/issues/7040 
That ticket is under stakeholder review for around a week

**Comment by davidplappert** [comment]
@hlee Please fix the failing build. Thanks!

**Comment by Kevin-Wei** [comment]
@hlee this branch needs a merge or rebase though it looks like a contingency ticket got added anyway

**Comment by hlee** [comment]
https://github.com/dchbx/enroll/pull/92

will be deploy from above one

**Comment by Kevin-Wei** [comment]
addressed via https://github.com/dchbx/enroll/pull/92

**Comment by Kevin-Wei** [comment]
@davidplappert any reason this PR got hit at the same time as https://github.com/dchbx/gluedb/pull/58 ?

**Pull request closed without merging**
